const express = require('express');
const router = express.Router();
const multer = require('multer');
const axios = require('axios');
const { getSupabase } = require('../supabaseClient');
const { auth } = require('../middleware/auth');
require('dotenv').config();

// Configuration
const upload = multer({
    storage: multer.memoryStorage(),
    limits: { fileSize: 5 * 1024 * 1024 }
});

// Use ONLY the X-ray specific API key as requested
const XRAY_API_KEY = process.env.XRAY_OPENROUTER_API_KEY;

const MODELS = [
    'google/gemma-3-27b-it:free',
    'qwen/qwen3-4b:free',
    'arcee-ai/trinity-large-preview:free'
];

/**
 * Optional Auth wrapper to not block the request if user is not logged in
 * but still capture the user info if they are.
 */
async function optionalAuth(req, res, next) {
    const authHeader = req.header('Authorization');
    if (authHeader) {
        return auth(req, res, next);
    }
    next();
}

/**
 * POST /api/analyze-xray
 * Analyzes X-ray image using OpenRouter fallback mechanism
 */
router.post('/analyze-xray', upload.single('file'), optionalAuth, async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ success: false, message: 'No file uploaded' });
        }

        if (!XRAY_API_KEY) {
            console.error('[XRayAnalysis] XRAY_OPENROUTER_API_KEY is missing');
            return res.status(500).json({
                success: false,
                message: 'Unable to analyze the X-ray. API key not configured.'
            });
        }

        // Temporary observation as requested for text generation
        const observationText = "Possible mild opacity detected in the lower lung region. Heart size appears normal.";

        console.log(`[XRayAnalysis] Starting parallel race for ${MODELS.length} models...`);

        // Create parallel "racer" promises
        const racers = MODELS.map(async (model) => {
            try {
                const response = await axios.post(
                    'https://openrouter.ai/api/v1/chat/completions',
                    {
                        model: model,
                        messages: [
                            {
                                role: "system",
                                content: `Act as an experienced radiologist. Think step-by-step like a doctor reading an X-ray in clinical practice.

Analyze the X-ray systematically using a clinical approach:
1. First assess image quality and visible anatomical structures.
2. Identify objective findings only (opacities, fractures, enlargements, fluid levels, asymmetry, abnormalities).
3. Interpret findings using medical reasoning based on radiology principles.
4. Provide the most likely diagnosis, followed by possible differential diagnoses if uncertainty exists.
5. Consider common conditions before rare ones.
6. Do not exaggerate severity without clear evidence.
7. Clearly mention limitations of X-ray and when further tests (CT, MRI, blood tests) may be needed.
8. Explain results in language understandable to a patient while maintaining medical accuracy.

Provide a detailed medical report based on the observations provided. Keep the response professional and strictly structured.

Your report MUST include:
- A confidence percentage.
- 4-5 common symptoms associated with the findings.
- 4-5 home remedies or recommended next steps.
- Exactly 3 recommended OTC medications with usage instructions (ONLY OTC, no prescription drugs).
- Exactly 4 critical points for when to see a doctor or seek urgent care.`
                            },
                            {
                                role: "user",
                                content: `Analyze this chest X-ray observation and generate a report: ${observationText}`
                            }
                        ],
                        max_tokens: 1000,
                        temperature: 0.3
                    },
                    {
                        headers: {
                            'Authorization': `Bearer ${XRAY_API_KEY}`,
                            'Content-Type': 'application/json',
                            'HTTP-Referer': 'https://medibridge.vercel.app',
                            'X-Title': 'MediBridge X-Ray AI'
                        },
                        timeout: 30000
                    }
                );

                const text = response.data?.choices?.[0]?.message?.content;
                if (text) {
                    return text;
                }
                throw new Error(`Model ${model} returned empty content`);
            } catch (err) {
                console.error(`[XRayAnalysis] Racer ${model} failed:`, err.message);
                throw err;
            }
        });

        let reportText = "";
        try {
            reportText = await Promise.any(racers);
            console.log(`[XRayAnalysis] Win! Report generated by fastest model.`);
        } catch (err) {
            console.error('[XRayAnalysis] All parallel racers failed.');
        }

        if (!reportText) {
            return res.status(500).json({
                success: false,
                message: `Unable to analyze the X-ray. Please try again.`
            });
        }

        // Save to prediction history if user is logged in
        if (req.user) {
            try {
                const supabaseClient = getSupabase(req.token);
                await supabaseClient
                    .from('symptom_history')
                    .insert({
                        user_id: req.user.id,
                        symptoms_input: ['Chest X-Ray Analysis'],
                        predicted_disease: 'X-Ray Report Generated',
                        confidence_score: 1.0,
                        severity: 'Refer to Report',
                        full_response: { report: reportText, type: 'xray' }
                    });
                console.log('[XRayAnalysis] Saved to prediction history');
            } catch (historyErr) {
                console.error('[XRayAnalysis] History save error:', historyErr.message);
            }
        }

        // Final response format requested by user
        res.json({
            success: true,
            report: reportText
        });

    } catch (error) {
        console.error('[XRayAnalysis] Global error:', error);
        res.status(500).json({
            success: false,
            message: 'Unable to analyze the X-ray. Please try again.'
        });
    }
});

module.exports = router;
